#!/usr/bin/env bash
#This Script Makes A  Custom 404 Page
# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create a custom 404 page
echo  "How are You Today?" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default
sudo service nginx restart
