#!/usr/bin/env bash
#This Script Makes A Header
# Install Nginx

sudo apt-get update
sudo apt-get install nginx -y

#Create a Hello World
echo "Hello World!" | sudo tee /var/www/html/index.html

#Create a Redirection
sudo sed -i '/server_name _;/a\    location /redirect_me {\n 	return 301 https://www.youtube.com/watch?v=QH2-TGUIwu4;\n } ' /etc/nginx/sites-available/default

# Create a custom 404 page
echo  "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configuring your Response Head
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default
sudo service nginx restart
