#!/usr/bin/env bash
# A Bash Script that copies a File to My Remote Sever using scp

if [ $# -lt 4 ]; then
	echo: "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#path_to_file=$1
#ip=$2
#username=$3
#pathtossh_key=$4

#Transfer the File To Server
scp -i "$4" -o StrictHostKeyChecking=No "$1" "$3@$2":~/
