#!/usr/bin/env bash
#This Bash Script installs A HAProxy LoadBalancer
# And configures frontend and backend in backonfig

#Updates Packages
sudo apt-get update

#Install HAProxy
sudo apt-get install haproxy -y

#Start HAProxy
sudo service haproxy start

#Configure HAProxy Configuration File
sudo tee -a /etc/haproxy/haproxy.cfg > dev/null <<EOT
frontend restinc-alx
		bind *:80
		default_backend restinc-servers


backend restinc-servers
		balance roundrobin
		server web-01 34.227.101.223:80 check
		server web-02 18.204.15.60:80 check
EOT

# Start HAProxy
sudo /etc/init.d/haproxy start

# HAProxy Reboot on Start
sudo update-rc.d haproxy defaults

# Restart HAProxy
sudo /etc/init.d/haproxy restart
