#!/usr/bin/env bash
#This Scripts print "Best School" using while loop and "Hi" 
#+after the 9th iteration

i=0
while [ "$i" -lt 10 ];
do
	if [ $i == 9 ]; 
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
