#!/usr/bin/env bash
#This Script prints "Best School"
#+ 4th iteration prints "Bad Luck"
#+ 8th iteration prints "Good Luck"

i=0
while [ "$i" -lt 10 ];
do
	if [ "$i" == 3 ]; then
		echo "bad Luck"
	elif [ "$i" == 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
	
done
