#!/usr/bin/env bash
#This bash resolves your localhost IP to 127.0.0.2 and Facebook.com to 8.8.8.8

cp /etc/hosts ~hosts.new
echo "127.0.0.2     localhost" >> ~hosts.new
echo "8.8.8.8       facebook" >> ~hosts.new
cp -f ~hosts.new /etc/hosts
