#!/usr/bin/env bash
#This Script configures nginx.conf

#Stop nginx and apache2
sudo service nginx stop
sudo pkill apache2

#Change user to nginx
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

#Change Defaulot Listening Port to 8080
sudo sed -i 's/listen 80 default_server;/#listen 8080 default_server;/' /etc/sites-available/default

#Change IPv6 Port 80 to 8080 
sudo sed -i 's/listen \[::\]:80/listen\[::]:8080/' /etc/sites-available/default

#Test Nginx Configuration without Starting Server
sudo nginx -t

#Start nginx
sudo service nginx start
